### ISSUE TITLE
Support Grafana >= 7.0.4

### ISSUE THREAD

**Issue by miry** [lightstep/lightstep-grafana-plugin#64]
In Grafana >=7.0.4 and 7.1.x there changes in Panel Editor to make it more strict.
The current version of plugin https://github.com/lightstep/lightstep-grafana-plugin/commit/fbb1fd4b4455b8ce70c63169a463ab392c06d2a2 tested against Grafana 7.0.3 and it works.

But in Grafana >=7.0.4 the row with options is missing:

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/21104/87829738-e664f800-c87f-11ea-958e-0e6434cf3388.png">

Image: grafana/grafana:7.1.0
Plugin version: https://github.com/lightstep/lightstep-grafana-plugin/commit/fbb1fd4b4455b8ce70c63169a463ab392c06d2a2

I assume the PR that makes a crutial changes to Panel Editor: https://github.com/grafana/grafana/pull/25653

**Comment by smithclay** [comment]
The latest release, v1.2.0, now supports Grafana 7 and 8.
