### ISSUE TITLE
Use securejsondata instead of jsonData for storing api key

### ISSUE THREAD

**Issue by theothertomelliott** [lightstep/lightstep-grafana-plugin#79]
Requesting the list of dashboards from the Grafana API (`/api/datasources`) has the API key stored in `jsonData`:

```
"jsonData": {
    "apiKey": "REDACTED",
    "dashboardURL": "https://app.lightstep.com",
    "organizationName": "MyOrg",
    "projectName": "myproj"
},
```

This exposes the credential in plaintext in the api and the database.

Storing the key in `secureJsonData` will encrypt it at rest and prevent it being returned when queried via the API.

```
"jsonData": {
    "dashboardURL": "https://app.lightstep.com",
    "organizationName": "MyOrg",
    "projectName": "myproj"
},
"secureJsonData": {
    "apiKey": "REDACTED",
},
```

**Comment by smithclay** [comment]
The latest release, v1.2.0, now stores the API token in `secureJsonData`.
