### ISSUE TITLE
Lightstep Graph panel throws critical error every refresh in Grafana 8.x

### ISSUE THREAD

**Issue by chrisleavoy** [lightstep/lightstep-grafana-plugin#90]
The `Lightstep Graph` panel throws an error in Grafana 8.x on dashboard load or time range change.

![image](https://user-images.githubusercontent.com/1428245/130281775-5dd4d1df-7689-4361-a9b5-d5588ed508d8.png)

Annotation Query Failed
Cannot read property 'to' of undefined

Verified in latest Grafana 8.1.2

**Comment by smithclay** [comment]
This should be fixed in `v1.2.3`: https://github.com/lightstep/lightstep-grafana-plugin/releases/tag/v1.2.3
